/**
 * 301s for every URL in the old Shopify sitemap (scripts/legacy-urls.txt).
 * Generated by scripts/gen-redirects.py — edit the rules there, not here.
 * The catch-alls in next.config.ts pick up Shopify paths the sitemap never listed.
 */
export const LEGACY_REDIRECTS: { source: string; destination: string }[] = [
  {
    "source": "/blogs/biking-blog",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/11-reasons-to-use-a-mobile-bike-shop-instead-of-going-to-a-store",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/7-most-common-bike-issues-we-fix-in-the-field",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/bentonville-bike-date-ideas",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/bentonville-bike-safety-guide",
    "destination": "/resources/safety-inspection-checklist"
  },
  {
    "source": "/blogs/biking-blog/bentonville-e-bike-community",
    "destination": "/solutions/e-bike-shops"
  },
  {
    "source": "/blogs/biking-blog/bentonville-mountain-bike-breweries",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/bentonville-mountain-biking-daily-routine-ride-and-repair-guide",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/bentonvilles-best-sunrise-ride-spots",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/best-after-work-mountain-bike-trails",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/best-coffee-shops-to-ride-to-in-bentonville",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/bike-co-bike-repair-on-the-go",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/bike-co-bike-to-work-commuters-nwa",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/bikepacking-bentonville-what-to-pack",
    "destination": "/resources/safety-inspection-checklist"
  },
  {
    "source": "/blogs/biking-blog/charging-on-the-go-ebike-tips",
    "destination": "/solutions/e-bike-shops"
  },
  {
    "source": "/blogs/biking-blog/coler-mountain-bike-tire-guide",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/blogs/biking-blog/day-in-the-life-of-a-mobile-bike-tech",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/diy-vs-pro-bike-repair-when-to-call-in-the-experts",
    "destination": "/solutions/repair-shops"
  },
  {
    "source": "/blogs/biking-blog/e-bike-maintenance-on-the-go",
    "destination": "/solutions/e-bike-shops"
  },
  {
    "source": "/blogs/biking-blog/extend-bike-life-with-regular-mobile-service",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/family-biking-in-bentonville",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/first-mobile-bike-service-what-to-expect",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/flat-tire-ozarks-mobile-bike-service",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/getting-kids-into-mountain-biking-bentonville",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/gravel-grinding-northwest-arkansas",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/hidden-mountain-bike-trails-bentonville-arkansas-guide",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/how-to-get-your-kids-bikes-trail-ready-this-summer",
    "destination": "/resources/safety-inspection-checklist"
  },
  {
    "source": "/blogs/biking-blog/how-to-prep-your-mountain-bike-for-slaughter-pen-trails",
    "destination": "/resources/safety-inspection-checklist"
  },
  {
    "source": "/blogs/biking-blog/how-to-protect-your-bike-components-when-riding-in-the-rain",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/blogs/biking-blog/inside-a-mobile-bike-repair-van-tools-parts-and-workshop-setup",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/inside-a-mobile-mechanics-kit",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/is-an-e-bike-right-for-bentonville-trails",
    "destination": "/solutions/e-bike-shops"
  },
  {
    "source": "/blogs/biking-blog/local-bike-routes-staff-picks-bike-co",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/meet-your-local-mobile-mechanic",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/mobile-bike-maintenance-bentonville",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/mobile-bike-repair-for-busy-riders",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/mobile-bike-repair-gift-for-cyclists",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/mobile-bike-repair-myths-busted",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/mobile-bike-repairs-in-bentonville",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/mobile-bike-service-vs-traditional-shop",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/mobile-bike-shop-customer-success-stories",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/mobile-bike-shop-saves-time-and-money",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/mobile-bike-tech-bentonville-parents",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/mobile-bottom-bracket-repair",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/oz-trails-bike-prep-checklist",
    "destination": "/resources/safety-inspection-checklist"
  },
  {
    "source": "/blogs/biking-blog/planning-a-group-ride-with-bike-co",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/pre-ride-bike-inspection-checklist",
    "destination": "/resources/safety-inspection-checklist"
  },
  {
    "source": "/blogs/biking-blog/seasonal-bike-maintenance-checklist-bentonville",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/blogs/biking-blog/spring-bike-cleaning-guide-bike-co",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/blogs/biking-blog/spring-bike-maintenance-checklist-mobile-friendly-tips",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/summer-riding-tips-to-keep-your-bike-and-body-cool",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/blogs/biking-blog/the-best-post-ride-hangouts-in-bentonville-arkansas",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/the-rise-of-e-bikes-in-bentonville-what-you-need-to-know",
    "destination": "/solutions/e-bike-shops"
  },
  {
    "source": "/blogs/biking-blog/top-10-trails-in-bentonville",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/we-come-to-you-bentonville-mobile-bike-service",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/weekend-trail-loops-local-riders-should-know",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/what-every-cyclist-should-carry",
    "destination": "/resources/safety-inspection-checklist"
  },
  {
    "source": "/blogs/biking-blog/what-happens-during-a-mobile-bike-tune-up",
    "destination": "/solutions/mobile-repair"
  },
  {
    "source": "/blogs/biking-blog/what-to-pack-for-a-bentonville-trail-day",
    "destination": "/resources/safety-inspection-checklist"
  },
  {
    "source": "/blogs/biking-blog/when-to-replace-bike-chain",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/blogs/biking-blog/where-to-ride-in-bentonville-in-an-hour",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/why-bentonville-is-the-mountain-biking-capital-of-the-midwest",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/why-bentonville-riders-never-run-out-of-trails",
    "destination": "/blog"
  },
  {
    "source": "/blogs/biking-blog/why-is-my-bike-chain-making-noise",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/blogs/biking-blog/why-we-built-bike-co-mobile-cycling-platform",
    "destination": "/about"
  },
  {
    "source": "/blogs/biking-blog/winter-bike-maintenance-tips-for-arkansas-riders",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/blogs/biking-blog/your-guide-to-biking-events-in-bentonville-this-season",
    "destination": "/blog"
  },
  {
    "source": "/blogs/news",
    "destination": "/blog"
  },
  {
    "source": "/blogs/news/how-to-know-when-your-bike-needs-a-tune-up",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/collections/best-sellers",
    "destination": "/"
  },
  {
    "source": "/collections/builds-bike-assembly",
    "destination": "/platform/plm"
  },
  {
    "source": "/collections/cargo",
    "destination": "/solutions/e-bike-shops"
  },
  {
    "source": "/collections/fitting-service",
    "destination": "/product/online-booking"
  },
  {
    "source": "/collections/installs",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/collections/misc",
    "destination": "/resources/labor-rate-guide"
  },
  {
    "source": "/collections/suspension-services",
    "destination": "/product/work-orders"
  },
  {
    "source": "/collections/trail",
    "destination": "/solutions/e-bike-shops"
  },
  {
    "source": "/collections/tune-ups",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/pages/about-us",
    "destination": "/about"
  },
  {
    "source": "/pages/builds-bike-assembly",
    "destination": "/platform/plm"
  },
  {
    "source": "/pages/contact",
    "destination": "/contact"
  },
  {
    "source": "/pages/data-sharing-opt-out",
    "destination": "/privacy#opting-out-of-data-sharing"
  },
  {
    "source": "/pages/fitting-service",
    "destination": "/product/online-booking"
  },
  {
    "source": "/pages/installs",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/pages/locations",
    "destination": "/contact"
  },
  {
    "source": "/pages/misc",
    "destination": "/resources/labor-rate-guide"
  },
  {
    "source": "/pages/privacy-policy",
    "destination": "/privacy"
  },
  {
    "source": "/pages/suspension-services",
    "destination": "/product/work-orders"
  },
  {
    "source": "/pages/terms-conditions",
    "destination": "/terms"
  },
  {
    "source": "/pages/tune-ups",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/products/60-day-warranty-bike-fit-follow-up-adjustments-only-for-bike-fits-within-60-days-of-the-original-bike-fitting-session-date",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/additional-dropper-services-available",
    "destination": "/product/work-orders"
  },
  {
    "source": "/products/additional-services-are-being-added-and-are-available",
    "destination": "/resources/labor-rate-guide"
  },
  {
    "source": "/products/advanced-bicycle-tune-up-road-tri-gravel-mtb-and-hybrid-bikes",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/products/advanced-mtb-bike-fit",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/advanced-road-gravel-or-hybrid-fit",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/advanced-triathlon-fit",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/air-rear-shocks",
    "destination": "/product/work-orders"
  },
  {
    "source": "/products/bicycle-assembly-custom-build-for-road-tri-gravel-and-hybrid-bikes",
    "destination": "/platform/plm"
  },
  {
    "source": "/products/bicycle-assembly-frameset-and-build-kit-for-road-tri-gravel-and-hybrid-bikes",
    "destination": "/platform/plm"
  },
  {
    "source": "/products/bicycle-assembly-new-bike-from-box-partially-pre-built-for-e-bikes",
    "destination": "/solutions/e-bike-shops"
  },
  {
    "source": "/products/bicycle-assembly-new-bike-from-box-partially-pre-built-for-road-tri-gravel-and-hybrid-bikes",
    "destination": "/platform/plm"
  },
  {
    "source": "/products/bicycle-assembly-super-bike-build-all-internal-routing-of-shift-cables-mechanical-or-electronic-shifting-and-mechanical-or-hydraulic-brakes-450-if-applicable-any-additional-cost-as-prescribed-below",
    "destination": "/platform/plm"
  },
  {
    "source": "/products/bicycle-disassembly-service",
    "destination": "/platform/plm"
  },
  {
    "source": "/products/bicycle-packaging-and-boxing-for-shipment-frameset",
    "destination": "/platform/plm"
  },
  {
    "source": "/products/bike-fit-free-bike-fit-assessment",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/coil-rear-shocks",
    "destination": "/product/work-orders"
  },
  {
    "source": "/products/elite-bicycle-tune-up-e-bike-bikes",
    "destination": "/solutions/e-bike-shops"
  },
  {
    "source": "/products/elite-bicycle-tune-up-road-tri-gravel-mtb-and-hybrid-bikes",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/products/forks",
    "destination": "/product/work-orders"
  },
  {
    "source": "/products/general-follow-up-bike-check",
    "destination": "/resources/safety-inspection-checklist"
  },
  {
    "source": "/products/heavy-blend-crewneck-sweatshirt-black",
    "destination": "/"
  },
  {
    "source": "/products/install-and-lube-both-new-brake-and-shifter-cables-housing-w-bike-tune-up-mechanical-internal-integrated-or-exterior-labor-only",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-and-lube-new-brake-cables-and-housing-mechanical-internal-integrated-or-exterior-labor-only",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-and-lube-new-shifter-cables-and-housing-mechanical-internal-integrated-or-exterior-labor-only",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-and-or-reroute-di2-handlebar-wires-purchased-at-oz%C2%AE-bike-fit-labor",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-and-or-reroute-di2-handlebar-wires-purchased-at-oz\u00ae-bike-fit-labor",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-bar-tape-purchased-at-oz%C2%AE-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-bar-tape-purchased-at-oz\u00ae-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-bar-tape-purchased-from-source-outside-of-oz%C2%AE-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-bar-tape-purchased-from-source-outside-of-oz\u00ae-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-cassette-swap-install-purchased-from-source-outside-of-oz%C2%AE-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-cassette-swap-install-purchased-from-source-outside-of-oz\u00ae-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-cassette-swap-install-purchased-oz%C2%AE-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-cassette-swap-install-purchased-oz\u00ae-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-crankset-purchased-from-oz%C2%AE-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-crankset-purchased-from-oz\u00ae-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-crankset-purchased-from-oz%C2%AE-bike-fit-1",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-crankset-purchased-from-oz\u00ae-bike-fit-1",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-bike-chain-purchased-from-oz%C2%AE-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-bike-chain-purchased-from-oz\u00ae-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-bike-chain-purchased-from-source-outside-of-oz%C2%AE-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-bike-chain-purchased-from-source-outside-of-oz\u00ae-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-handlebars-purchased-at-oz%C2%AE-bike-fit-and-route-re-route-wires-or-cables-housing",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-handlebars-purchased-at-oz\u00ae-bike-fit-and-route-re-route-wires-or-cables-housing",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-handlebars-purchased-from-a-source-outside-of-oz%C2%AE-bike-fit-and-route-re-route-wires-or-cables-housing",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-handlebars-purchased-from-a-source-outside-of-oz\u00ae-bike-fit-and-route-re-route-wires-or-cables-housing",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-stem-headset-components",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-tire-and-or-tube-tubed-clinchers-purchased-from-source-outside-of-oz%C2%AE-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-tire-and-or-tube-tubed-clinchers-purchased-from-source-outside-of-oz\u00ae-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-tire-and-or-tube-tubed-clinchers-tire-and-tube-purchased-from-oz%C2%AE-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-new-tire-and-or-tube-tubed-clinchers-tire-and-tube-purchased-from-oz\u00ae-bike-fit",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-rewrap-handlebar-tape-w-current-tape",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-seat-post-cut-down",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/install-tubeless-tire-set-up-new-or-remount-per-wheel",
    "destination": "/product/parts-inventory"
  },
  {
    "source": "/products/lightweight-windbreaker-black-forest-camo",
    "destination": "/"
  },
  {
    "source": "/products/long-sleeve-t-shirt-black",
    "destination": "/"
  },
  {
    "source": "/products/new-bike-saddle-selection-fit",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/per-hour-labor-charge-for-special-customizations-outside-of-normal-bike-fit-adjustments-application",
    "destination": "/resources/labor-rate-guide"
  },
  {
    "source": "/products/poly-tech-soft-shell-jacket",
    "destination": "/"
  },
  {
    "source": "/products/pre-bike-purchase-fit-spec-research-analysis-outside-of-an-original-pre-bike-fitting-service-or-a-premier-bike-fitting-on-additional-bike-of-like-type-cost-based-upon-75-hr-rate",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/pre-bike-purchase-sizing-fit-only",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/pre-bike-purchase-sizing-fit-w-premier-fit",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/pre-race-ride-safety-inspection-for-road-tri-gravel-mtb-and-hybrid-bikes",
    "destination": "/resources/safety-inspection-checklist"
  },
  {
    "source": "/products/premier-mtb-fit-cleats-to-seat-suspension",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/premier-road-gravel-or-hybrid-fit-cleats-to-seat",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/premier-triathlon-fit-cleats-to-seat",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/pro-bicycle-tune-up-road-tri-gravel-mtb-and-hybrid-bikes",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/products/psc-pedal-shoe-cleat-combo-fit-only",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/radrunner-2",
    "destination": "/solutions/e-bike-shops"
  },
  {
    "source": "/products/radster-trail",
    "destination": "/solutions/e-bike-shops"
  },
  {
    "source": "/products/rear-shocks",
    "destination": "/product/work-orders"
  },
  {
    "source": "/products/rectangle-woven-flannel-shirt-long-sleeve-black-gray",
    "destination": "/"
  },
  {
    "source": "/products/refresh-standard-clean-re-lube-and-reset",
    "destination": "/product/work-orders"
  },
  {
    "source": "/products/services-not-previously-set-upfront-may-be-available-on-an-hourly-basis-at-65-hour",
    "destination": "/resources/labor-rate-guide"
  },
  {
    "source": "/products/session-to-review-current-fit-and-consultation-on-bike-fittings-cost-based-upon-75-hr-rate",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/specs-coordinate-application-to-a-new-bike-or-2nd-bike-of-the-same-type-from-a-previous-oz-bike-fit-session",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/standard-bicycle-tune-up-road-tri-gravel-mtb-and-hybrid-bikes",
    "destination": "/resources/tune-up-checklist"
  },
  {
    "source": "/products/standard-road-gravel-or-hybrid-fit",
    "destination": "/product/online-booking"
  },
  {
    "source": "/products/sweatshirt-black",
    "destination": "/"
  },
  {
    "source": "/products/t-shirt-black",
    "destination": "/"
  },
  {
    "source": "/products/woven-snapback-trucker-hat-heather-gray-black",
    "destination": "/"
  }
]
