"""Build data/redirects.ts from scripts/legacy-urls.txt (the old Shopify sitemap)."""
import json, re, urllib.parse
urls = [l.strip() for l in open('scripts/legacy-urls.txt') if l.strip()]

EXACT = {
  '/pages/contact': '/contact', '/pages/about-us': '/about', '/pages/locations': '/contact',
  '/pages/privacy-policy': '/privacy', '/pages/terms-conditions': '/terms',
  '/pages/data-sharing-opt-out': '/privacy#opting-out-of-data-sharing',
  '/pages/fitting-service': '/product/online-booking', '/collections/fitting-service': '/product/online-booking',
  '/pages/suspension-services': '/product/work-orders', '/collections/suspension-services': '/product/work-orders',
  '/pages/tune-ups': '/resources/tune-up-checklist', '/collections/tune-ups': '/resources/tune-up-checklist',
  '/pages/builds-bike-assembly': '/platform/plm', '/collections/builds-bike-assembly': '/platform/plm',
  '/pages/installs': '/product/parts-inventory', '/collections/installs': '/product/parts-inventory',
  '/pages/misc': '/resources/labor-rate-guide', '/collections/misc': '/resources/labor-rate-guide',
  '/collections/best-sellers': '/', '/collections/trail': '/solutions/e-bike-shops', '/collections/cargo': '/solutions/e-bike-shops',
  '/blogs/news': '/blog', '/blogs/biking-blog': '/blog',
  '/blogs/biking-blog/why-we-built-bike-co-mobile-cycling-platform': '/about',
  '/blogs/biking-blog/diy-vs-pro-bike-repair-when-to-call-in-the-experts': '/solutions/repair-shops',
  '/blogs/biking-blog/mobile-bike-shop-customer-success-stories': '/solutions/mobile-repair',
}

def product(slug):
    s = urllib.parse.unquote(slug)
    if re.search(r'radster|radrunner|(^|-)e-bike', s): return '/solutions/e-bike-shops'
    if re.search(r'shirt|jacket|windbreaker|-hat-', s): return '/'
    if re.search(r'pre-race|safety-inspection|follow-up-bike-check', s): return '/resources/safety-inspection-checklist'
    if 'tune-up' in s and not s.startswith('install'): return '/resources/tune-up-checklist'
    if re.search(r'^(forks|rear-shocks|coil-rear-shocks|air-rear-shocks|refresh|additional-dropper)', s): return '/product/work-orders'
    if re.search(r'assembly|disassembly|packaging', s): return '/platform/plm'
    if s.startswith('install'): return '/product/parts-inventory'
    if re.search(r'per-hour-labor|services-not-previously|additional-services', s): return '/resources/labor-rate-guide'
    if 'fit' in s or 'session-to-review' in s: return '/product/online-booking'
    return '/product'

def post(slug):
    if re.search(r'(^|-)(e-bike|ebike)', slug): return '/solutions/e-bike-shops'
    if re.search(r'mobile|on-the-go|we-come-to-you|in-the-field|mechanic|repair-van|bike-tech|busy-riders|planning-a-group-ride', slug): return '/solutions/mobile-repair'
    if re.search(r'inspection|safety|prep|trail-ready|what-to-pack|carry', slug): return '/resources/safety-inspection-checklist'
    if re.search(r'tune-up|maintenance|chain|bottom-bracket|cleaning|components|tire|winter|summer|rain|extend-bike-life', slug): return '/resources/tune-up-checklist'
    return '/blog'

out = []
for u in urls:
    path = urllib.parse.unquote(u)
    if u in EXACT: dest = EXACT[u]
    elif u.startswith('/products/'): dest = product(u.split('/')[-1])
    elif u.startswith('/blogs/'): dest = post(u.split('/')[-1])
    else: raise SystemExit(f'unmapped {u}')
    out.append({'source': u, 'destination': dest})
    if path != u: out.append({'source': path, 'destination': dest})

src = '''/**
 * 301s for every URL in the old Shopify sitemap (scripts/legacy-urls.txt).
 * Generated by scripts/gen-redirects.py — edit the rules there, not here.
 * The catch-alls in next.config.ts pick up Shopify paths the sitemap never listed.
 */
export const LEGACY_REDIRECTS: { source: string; destination: string }[] = %s
''' % json.dumps(out, indent=2)
open('data/redirects.ts', 'w').write(src)
from collections import Counter
print(len(urls), 'urls ->', len(out), 'rules'); [print(f'{n:3} {d}') for d, n in Counter(o['destination'] for o in out).most_common()]
